name: Deploy User Interface

on:
  push:
    paths:
    - 'ui/**'

env:
  AZURE_WEBAPP_PACKAGE_PATH: './ui'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        refs: ${{ github.ref }}

    - name: Copy Python source files to UI folder
      run: '(test -d ./src && cp -vrf ./src/* ./ui) || echo ./src is empty, skipping'

    - name: Deploy to Azure Web App (master)
      uses: Azure/webapps-deploy@v2
      if: endsWith(github.ref, 'master')
      with:
        app-name: unisa-tbi
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_master }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Web App (Niki)
      uses: Azure/webapps-deploy@v2
      if: endsWith(github.ref, 'Niki')
      with:
        app-name: unisa-tbi-niki
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_Niki }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Web App (Bhavya)
      uses: Azure/webapps-deploy@v2
      if: endsWith(github.ref, 'Bhavya')
      with:
        app-name: unisa-tbi-bhavya
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_Bhavya }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Web App (Karthik)
      uses: Azure/webapps-deploy@v2
      if: endsWith(github.ref, 'Karthik')
      with:
        app-name: unisa-tbi-karthik
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_Karthik }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
#     - name: Deploy to Azure Web App (jan)
#       uses: Azure/webapps-deploy@v2
#       if: endsWith(github.ref, 'jan')
#       with:
#         app-name: unisa-tbi-jan
#         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_jan }}
#         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
